[Build][Android] Fix Android SDK env prepare scripts
**Background**
The Android SDK download that this repo uses for CI environment preparation is quite old and only runs on Java 8 while the CI builders have migrated to Java 11 which leads to a failure when trying to accept SDK licences:
```
2022-04-13 09:34:44 Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
2022-04-13 09:34:44 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
2022-04-13 09:34:44 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
2022-04-13 09:34:44 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
2022-04-13 09:34:44 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
2022-04-13 09:34:44 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
2022-04-13 09:34:44 Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
2022-04-13 09:34:44 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
2022-04-13 09:34:44 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2022-04-13 09:34:44 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
2022-04-13 09:34:44 	... 5 more
``` 

**Change**
- Use latest sdk tools download links and checksums. 
- Move the sdk tools to an expected directory similar like it is done in: https://github.sc-corp.net/Snapchat/android/blob/a650e41c73679c3ca49ca3075d53ee21fa58aa76/jenkins/envPrepare.sh#L31

**Test Plan**
- Build on CI

**Checklist**
- [x] I have updated the documentation accordingly when applicable: sample app code and documentation READMEs are kept in sync with any changes brought in by a new SDK version.
- [x] I have updated the **Unreleased** section in the [CHANGELOG.md](https://github.sc-corp.net/Snapchat/camera-kit-distribution/blob/master/CHANGELOG.md) to include entries that describe changes that this PR introduces.
---
Automatic squash commit from https://github.sc-corp.net/Snapchat/camera-kit-distribution/pull/722
Cooled by jokubas-dargis